name: Publish canary release

on:
  push:
    branches:
      - dev

jobs:
  run-tests:
    name: Run tests
    uses: ./.github/workflows/ci.yml
    secrets:
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

  canary:
    name: Create and publish a new release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - run: npm install
      - run: npm run build

      - name: Configure NPM
        run: npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}

      - name: Publish canary release
        run: |
          npm run version:canary
          npm run release:canary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
