name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    paths:
      - 'minisite/**'
    branches:
      - 'main'
      - 'dev'

jobs:
  build:
    name: 'Build the minisite'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - run: npm install
      - run: npm run build
      - run: npm -w minisite run build

      - uses: actions/upload-pages-artifact@v2
        with:
          path: 'minisite/dist/'

  deploy:
    name: 'Deploy to GitHub Pages'
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
