#!/usr/bin/env bash

set -euo pipefail

project_dir=$(realpath "$(dirname $0)/..")
source_dir="$project_dir/src/apps/capture"
build_dir="$project_dir/dist/capture"

flags="--config webpack.capture.config.js"
watch=false

while getopts "w" param; do
  case "$param" in
    w) watch=true;;
  esac
done

if [ "$watch" = true ]; then
  flags="$flags --watch"
fi

mkdir -p "$build_dir"

cp -r $source_dir/extension/static/* $build_dir/

eval "npx webpack $flags"
