apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: repro-localhost-wildcard
  namespace: default
spec:
  secretName: repro-localhost-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  commonName: "*.repro.localhost"
  dnsNames:
  - "*.repro.localhost"
  - "repro.localhost"
