#!/usr/bin/env bash

set -euo pipefail

project_dir=$(realpath "$(dirname $0)/..")
output_dir=$project_dir/dist

cd $project_dir

pnpx esbuild \
  `find src -regextype posix-extended \\( \
    -regex '.*/.*\.tsx?$' \
    -and ! -regex '.*/.*\.bench.tsx?$' \
    -and ! -regex '.*/.*\.test.tsx?$' \
  \\)` \
  --format=cjs \
  --outdir=$output_dir

pnpx tsc-alias --outDir $output_dir
