#!/usr/bin/env bash

set -euo pipefail

project_dir=$(realpath "$(dirname $0)/..")
source_dir="$project_dir/src"
build_dir="$project_dir/dist"

flags="--bundle --platform=node --outdir=$build_dir"
watch=false
entries="index.ts"

while getopts "w" param; do
  case "$param" in
    w) watch=true;;
  esac
done

if [ "$watch" = true ]; then
  flags="$flags --watch"
fi

mkdir -p "$build_dir"

eval "(cd $source_dir && npx esbuild $entries $flags)"
