ingress:
  className: nginx

  appRoutes:
    host: app.repro.localhost
    annotations:
      nginx.ingress.kubernetes.io/app-root: /w
    paths:
      - path: /w(/|$)(.*)
        pathType: ImplementationSpecific
        serviceName: workspace-service
        servicePort: 8443
      - path: /s(/|$)(.*)
        pathType: ImplementationSpecific
        serviceName: public-playback-ui-service
        servicePort: 8443
  
  apiRoutes:
    host: api.repro.localhost
    paths:
      - path: /s(/|$)(.*)
        pathType: ImplementationSpecific
        serviceName: public-api-server-service
        servicePort: 8080
  
  adminRoutes:
    host: admin.repro.localhost
    paths:
      - path: /(.*)
        pathType: ImplementationSpecific
        serviceName: admin-service
        servicePort: 8080
