# Default values for gateway chart
gateway:
  image: gateway-nginx
  replicas: 1
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations: {}
  
  # Routes to the gateway service
  routes:
    - path: /
      pathType: Prefix
      serviceName: gateway-service
      servicePort: 80
