apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.gateway.port }}
    targetPort: {{ .Values.gateway.port }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Release.Name }}
