name: Build, lint and test
on: workflow_dispatch
jobs:
  run-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - name: Setup Node.js with caching
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Get Nx cache
        uses: actions/cache@v3
        with:
          path: .nx-cache
          key: ${{ runner.os }}-nx-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-nx-

      - name: Build all packages and apps
        run: pnpm nx run-many -t build

      - name: Typecheck all
        run: pnpm nx run-many -t typecheck
