name: Build, lint and test
on: workflow_dispatch
jobs:
  run-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: true

      - name: Build packages
        run: pnpm nx run-many -t build --projects=packages/*

      - name: Build workspace app
        run: pnpm dotenvx -f apps/workspace/.env.ci -- nx run @repro/workspace:build

      - name: Typecheck all
        run: pnpm nx run-many -t typecheck
