name: Production - workspace build & deploy

on:
  push:
    branches:
      - main
    paths:
      - apps/client/**
      - packages/**
      - .github/workflows/prod-workspace.yml

jobs:
  build:
    name: Build Repro workspace client

    runs-on: ubuntu-20.04

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Load NX build cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.nx-cache
          key: nx-build-cache

      - name: Setup toolchain
        uses: asdf-vm/actions/install@v2

      - name: Install dependencies and prepare packages
        run: pnpm install

      - name: Build workspace client
        run: pnpm nx run @repro/client:build:main
        env:
          BUILD_ENV: production
          PADDLE_VENDOR_ID: ${{ secrets.PADDLE_VENDOR_ID }}
          MIXPANEL_API_URL: https://api-eu.mixpanel.com
          MIXPANEL_TOKEN: ${{ secrets.MIXPANEL_TOKEN }}
          REPRO_APP_URL: https://app.repro.dev
          REPRO_API_URL: https://api.repro.dev
          AUTH_STORAGE: local-storage
          STATS_LEVEL: error

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          credentials_json: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Publish to cloud storage
        run: |
          gsutil -m \
            -h "Cache-Control: no-cache" \
            rsync -d -r apps/client/dist/main \
            gs://repro-deployments/workspace/builds/production
