name: Typecheck all packages
on: workflow_dispatch
jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: true

      - name: Run typecheck on all packages
        run: pnpm nx run-many -t typecheck
