name: Workspace branch build & deploy
run-name: Workspace branch build started by @${{ github.actor }} 

on:
  push:
    paths:
      - apps/client/**
      - packages/**

jobs:
  build:
    runs-on: ubuntu-20.04
    
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set variables
        id: vars
        run: |
          echo "::set-output name=branch::$(git branch --show-current | sed 's/\//_/g')"

      - name: Load NX build cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.nx-cache
          key: nx-build-cache

      - name: Setup toolchain
        uses: asdf-vm/actions/install@v2

      - name: Install dependencies and prepare packages
        run: pnpm install

      - name: Build workspace client
        run: pnpm nx run @repro/client:build:main
        env:
          BUILD_ENV: production
          PADDLE_VENDOR_ID: ${{ secrets.PADDLE_VENDOR_ID }}
          MIXPANEL_API_URL: https://api-eu.mixpanel.com
          MIXPANEL_TOKEN: ${{ secrets.MIXPANEL_TOKEN }}
          REPRO_APP_URL: https://app-preview.repro.dev/branch/${{ steps.vars.outputs.branch }}
          REPRO_API_URL: https://api.repro.dev
          AUTH_STORAGE: local-storage
          STATS_LEVEL: error

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          credentials_json: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Publish to cloud storage
        run: |
          gsutil -m \
            -h "Cache-Control: no-cache" \
            rsync -d -r apps/client/dist/main \
            gs://repro-workspace-builds/branch/${{ steps.vars.outputs.branch }}
